<script type="text/javascript" src="<?php echo base_url('public/js/jquery-2.1.1.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/chosen.jquery.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/jquery-ui.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/footable.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/footable.sort.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/footable.paginate.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/jquery.scrollTo.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/script-reservasi.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/js/ajax.js'); ?>"></script>